//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace app_ITP_client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name Nume from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdaugareClienti", ReplyAction="*")]
        app_ITP_client.ServiceReference1.AdaugareClientiResponse AdaugareClienti(app_ITP_client.ServiceReference1.AdaugareClientiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdaugareClienti", ReplyAction="*")]
        System.Threading.Tasks.Task<app_ITP_client.ServiceReference1.AdaugareClientiResponse> AdaugareClientiAsync(app_ITP_client.ServiceReference1.AdaugareClientiRequest request);
        
        // CODEGEN: Generating message contract since element name Nume from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdaugareInspectori", ReplyAction="*")]
        app_ITP_client.ServiceReference1.AdaugareInspectoriResponse AdaugareInspectori(app_ITP_client.ServiceReference1.AdaugareInspectoriRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdaugareInspectori", ReplyAction="*")]
        System.Threading.Tasks.Task<app_ITP_client.ServiceReference1.AdaugareInspectoriResponse> AdaugareInspectoriAsync(app_ITP_client.ServiceReference1.AdaugareInspectoriRequest request);
        
        // CODEGEN: Generating message contract since element name Marca from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdaugareVehicule", ReplyAction="*")]
        app_ITP_client.ServiceReference1.AdaugareVehiculeResponse AdaugareVehicule(app_ITP_client.ServiceReference1.AdaugareVehiculeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdaugareVehicule", ReplyAction="*")]
        System.Threading.Tasks.Task<app_ITP_client.ServiceReference1.AdaugareVehiculeResponse> AdaugareVehiculeAsync(app_ITP_client.ServiceReference1.AdaugareVehiculeRequest request);
        
        // CODEGEN: Generating message contract since element name DataProgramare from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdaugareProgramare", ReplyAction="*")]
        app_ITP_client.ServiceReference1.AdaugareProgramareResponse AdaugareProgramare(app_ITP_client.ServiceReference1.AdaugareProgramareRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdaugareProgramare", ReplyAction="*")]
        System.Threading.Tasks.Task<app_ITP_client.ServiceReference1.AdaugareProgramareResponse> AdaugareProgramareAsync(app_ITP_client.ServiceReference1.AdaugareProgramareRequest request);
        
        // CODEGEN: Generating message contract since element name Status from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdaugareRezultateInspectii", ReplyAction="*")]
        app_ITP_client.ServiceReference1.AdaugareRezultateInspectiiResponse AdaugareRezultateInspectii(app_ITP_client.ServiceReference1.AdaugareRezultateInspectiiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdaugareRezultateInspectii", ReplyAction="*")]
        System.Threading.Tasks.Task<app_ITP_client.ServiceReference1.AdaugareRezultateInspectiiResponse> AdaugareRezultateInspectiiAsync(app_ITP_client.ServiceReference1.AdaugareRezultateInspectiiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StergereProgramare", ReplyAction="*")]
        void StergereProgramare(int Id_Programare);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StergereProgramare", ReplyAction="*")]
        System.Threading.Tasks.Task StergereProgramareAsync(int Id_Programare);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StergereRezultateInspectii", ReplyAction="*")]
        void StergereRezultateInspectii(int Id_Inspectie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StergereRezultateInspectii", ReplyAction="*")]
        System.Threading.Tasks.Task StergereRezultateInspectiiAsync(int Id_Inspectie);
        
        // CODEGEN: Generating message contract since element name DataProgramare from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificareProgramare", ReplyAction="*")]
        app_ITP_client.ServiceReference1.ModificareProgramareResponse ModificareProgramare(app_ITP_client.ServiceReference1.ModificareProgramareRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificareProgramare", ReplyAction="*")]
        System.Threading.Tasks.Task<app_ITP_client.ServiceReference1.ModificareProgramareResponse> ModificareProgramareAsync(app_ITP_client.ServiceReference1.ModificareProgramareRequest request);
        
        // CODEGEN: Generating message contract since element name Nume from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificareClienti", ReplyAction="*")]
        app_ITP_client.ServiceReference1.ModificareClientiResponse ModificareClienti(app_ITP_client.ServiceReference1.ModificareClientiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificareClienti", ReplyAction="*")]
        System.Threading.Tasks.Task<app_ITP_client.ServiceReference1.ModificareClientiResponse> ModificareClientiAsync(app_ITP_client.ServiceReference1.ModificareClientiRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdaugareClientiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdaugareClienti", Namespace="http://tempuri.org/", Order=0)]
        public app_ITP_client.ServiceReference1.AdaugareClientiRequestBody Body;
        
        public AdaugareClientiRequest() {
        }
        
        public AdaugareClientiRequest(app_ITP_client.ServiceReference1.AdaugareClientiRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AdaugareClientiRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Id_Client;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Nume;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Prenume;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Telefon;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Email;
        
        public AdaugareClientiRequestBody() {
        }
        
        public AdaugareClientiRequestBody(int Id_Client, string Nume, string Prenume, string Telefon, string Email) {
            this.Id_Client = Id_Client;
            this.Nume = Nume;
            this.Prenume = Prenume;
            this.Telefon = Telefon;
            this.Email = Email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdaugareClientiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdaugareClientiResponse", Namespace="http://tempuri.org/", Order=0)]
        public app_ITP_client.ServiceReference1.AdaugareClientiResponseBody Body;
        
        public AdaugareClientiResponse() {
        }
        
        public AdaugareClientiResponse(app_ITP_client.ServiceReference1.AdaugareClientiResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AdaugareClientiResponseBody {
        
        public AdaugareClientiResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdaugareInspectoriRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdaugareInspectori", Namespace="http://tempuri.org/", Order=0)]
        public app_ITP_client.ServiceReference1.AdaugareInspectoriRequestBody Body;
        
        public AdaugareInspectoriRequest() {
        }
        
        public AdaugareInspectoriRequest(app_ITP_client.ServiceReference1.AdaugareInspectoriRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AdaugareInspectoriRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Id_Inspector;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Nume;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Prenume;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Specializare;
        
        public AdaugareInspectoriRequestBody() {
        }
        
        public AdaugareInspectoriRequestBody(int Id_Inspector, string Nume, string Prenume, string Specializare) {
            this.Id_Inspector = Id_Inspector;
            this.Nume = Nume;
            this.Prenume = Prenume;
            this.Specializare = Specializare;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdaugareInspectoriResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdaugareInspectoriResponse", Namespace="http://tempuri.org/", Order=0)]
        public app_ITP_client.ServiceReference1.AdaugareInspectoriResponseBody Body;
        
        public AdaugareInspectoriResponse() {
        }
        
        public AdaugareInspectoriResponse(app_ITP_client.ServiceReference1.AdaugareInspectoriResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AdaugareInspectoriResponseBody {
        
        public AdaugareInspectoriResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdaugareVehiculeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdaugareVehicule", Namespace="http://tempuri.org/", Order=0)]
        public app_ITP_client.ServiceReference1.AdaugareVehiculeRequestBody Body;
        
        public AdaugareVehiculeRequest() {
        }
        
        public AdaugareVehiculeRequest(app_ITP_client.ServiceReference1.AdaugareVehiculeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AdaugareVehiculeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id_Vehicul;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Marca;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Model;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string AnFabricatie;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string NumarInmatriculare;
        
        public AdaugareVehiculeRequestBody() {
        }
        
        public AdaugareVehiculeRequestBody(int id_Vehicul, string Marca, string Model, string AnFabricatie, string NumarInmatriculare) {
            this.id_Vehicul = id_Vehicul;
            this.Marca = Marca;
            this.Model = Model;
            this.AnFabricatie = AnFabricatie;
            this.NumarInmatriculare = NumarInmatriculare;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdaugareVehiculeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdaugareVehiculeResponse", Namespace="http://tempuri.org/", Order=0)]
        public app_ITP_client.ServiceReference1.AdaugareVehiculeResponseBody Body;
        
        public AdaugareVehiculeResponse() {
        }
        
        public AdaugareVehiculeResponse(app_ITP_client.ServiceReference1.AdaugareVehiculeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AdaugareVehiculeResponseBody {
        
        public AdaugareVehiculeResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdaugareProgramareRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdaugareProgramare", Namespace="http://tempuri.org/", Order=0)]
        public app_ITP_client.ServiceReference1.AdaugareProgramareRequestBody Body;
        
        public AdaugareProgramareRequest() {
        }
        
        public AdaugareProgramareRequest(app_ITP_client.ServiceReference1.AdaugareProgramareRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AdaugareProgramareRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Id_Programare;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DataProgramare;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string OraProgramare;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string id_Vehicul;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Id_Client;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Id_Inspector;
        
        public AdaugareProgramareRequestBody() {
        }
        
        public AdaugareProgramareRequestBody(int Id_Programare, string DataProgramare, string OraProgramare, string id_Vehicul, string Id_Client, string Id_Inspector) {
            this.Id_Programare = Id_Programare;
            this.DataProgramare = DataProgramare;
            this.OraProgramare = OraProgramare;
            this.id_Vehicul = id_Vehicul;
            this.Id_Client = Id_Client;
            this.Id_Inspector = Id_Inspector;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdaugareProgramareResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdaugareProgramareResponse", Namespace="http://tempuri.org/", Order=0)]
        public app_ITP_client.ServiceReference1.AdaugareProgramareResponseBody Body;
        
        public AdaugareProgramareResponse() {
        }
        
        public AdaugareProgramareResponse(app_ITP_client.ServiceReference1.AdaugareProgramareResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AdaugareProgramareResponseBody {
        
        public AdaugareProgramareResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdaugareRezultateInspectiiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdaugareRezultateInspectii", Namespace="http://tempuri.org/", Order=0)]
        public app_ITP_client.ServiceReference1.AdaugareRezultateInspectiiRequestBody Body;
        
        public AdaugareRezultateInspectiiRequest() {
        }
        
        public AdaugareRezultateInspectiiRequest(app_ITP_client.ServiceReference1.AdaugareRezultateInspectiiRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AdaugareRezultateInspectiiRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Id_Inspectie;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Status;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Observatii;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Id_Programare;
        
        public AdaugareRezultateInspectiiRequestBody() {
        }
        
        public AdaugareRezultateInspectiiRequestBody(int Id_Inspectie, string Status, string Observatii, string Id_Programare) {
            this.Id_Inspectie = Id_Inspectie;
            this.Status = Status;
            this.Observatii = Observatii;
            this.Id_Programare = Id_Programare;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdaugareRezultateInspectiiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdaugareRezultateInspectiiResponse", Namespace="http://tempuri.org/", Order=0)]
        public app_ITP_client.ServiceReference1.AdaugareRezultateInspectiiResponseBody Body;
        
        public AdaugareRezultateInspectiiResponse() {
        }
        
        public AdaugareRezultateInspectiiResponse(app_ITP_client.ServiceReference1.AdaugareRezultateInspectiiResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AdaugareRezultateInspectiiResponseBody {
        
        public AdaugareRezultateInspectiiResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificareProgramareRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificareProgramare", Namespace="http://tempuri.org/", Order=0)]
        public app_ITP_client.ServiceReference1.ModificareProgramareRequestBody Body;
        
        public ModificareProgramareRequest() {
        }
        
        public ModificareProgramareRequest(app_ITP_client.ServiceReference1.ModificareProgramareRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificareProgramareRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Id_Programare;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DataProgramare;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string OraProgramare;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int id_Vehicul;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int Id_Client;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int Id_Inspector;
        
        public ModificareProgramareRequestBody() {
        }
        
        public ModificareProgramareRequestBody(int Id_Programare, string DataProgramare, string OraProgramare, int id_Vehicul, int Id_Client, int Id_Inspector) {
            this.Id_Programare = Id_Programare;
            this.DataProgramare = DataProgramare;
            this.OraProgramare = OraProgramare;
            this.id_Vehicul = id_Vehicul;
            this.Id_Client = Id_Client;
            this.Id_Inspector = Id_Inspector;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificareProgramareResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificareProgramareResponse", Namespace="http://tempuri.org/", Order=0)]
        public app_ITP_client.ServiceReference1.ModificareProgramareResponseBody Body;
        
        public ModificareProgramareResponse() {
        }
        
        public ModificareProgramareResponse(app_ITP_client.ServiceReference1.ModificareProgramareResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ModificareProgramareResponseBody {
        
        public ModificareProgramareResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificareClientiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificareClienti", Namespace="http://tempuri.org/", Order=0)]
        public app_ITP_client.ServiceReference1.ModificareClientiRequestBody Body;
        
        public ModificareClientiRequest() {
        }
        
        public ModificareClientiRequest(app_ITP_client.ServiceReference1.ModificareClientiRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificareClientiRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Id_Client;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Nume;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Prenume;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Telefon;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Email;
        
        public ModificareClientiRequestBody() {
        }
        
        public ModificareClientiRequestBody(int Id_Client, string Nume, string Prenume, string Telefon, string Email) {
            this.Id_Client = Id_Client;
            this.Nume = Nume;
            this.Prenume = Prenume;
            this.Telefon = Telefon;
            this.Email = Email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificareClientiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificareClientiResponse", Namespace="http://tempuri.org/", Order=0)]
        public app_ITP_client.ServiceReference1.ModificareClientiResponseBody Body;
        
        public ModificareClientiResponse() {
        }
        
        public ModificareClientiResponse(app_ITP_client.ServiceReference1.ModificareClientiResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ModificareClientiResponseBody {
        
        public ModificareClientiResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : app_ITP_client.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<app_ITP_client.ServiceReference1.WebService1Soap>, app_ITP_client.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        app_ITP_client.ServiceReference1.AdaugareClientiResponse app_ITP_client.ServiceReference1.WebService1Soap.AdaugareClienti(app_ITP_client.ServiceReference1.AdaugareClientiRequest request) {
            return base.Channel.AdaugareClienti(request);
        }
        
        public void AdaugareClienti(int Id_Client, string Nume, string Prenume, string Telefon, string Email) {
            app_ITP_client.ServiceReference1.AdaugareClientiRequest inValue = new app_ITP_client.ServiceReference1.AdaugareClientiRequest();
            inValue.Body = new app_ITP_client.ServiceReference1.AdaugareClientiRequestBody();
            inValue.Body.Id_Client = Id_Client;
            inValue.Body.Nume = Nume;
            inValue.Body.Prenume = Prenume;
            inValue.Body.Telefon = Telefon;
            inValue.Body.Email = Email;
            app_ITP_client.ServiceReference1.AdaugareClientiResponse retVal = ((app_ITP_client.ServiceReference1.WebService1Soap)(this)).AdaugareClienti(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<app_ITP_client.ServiceReference1.AdaugareClientiResponse> app_ITP_client.ServiceReference1.WebService1Soap.AdaugareClientiAsync(app_ITP_client.ServiceReference1.AdaugareClientiRequest request) {
            return base.Channel.AdaugareClientiAsync(request);
        }
        
        public System.Threading.Tasks.Task<app_ITP_client.ServiceReference1.AdaugareClientiResponse> AdaugareClientiAsync(int Id_Client, string Nume, string Prenume, string Telefon, string Email) {
            app_ITP_client.ServiceReference1.AdaugareClientiRequest inValue = new app_ITP_client.ServiceReference1.AdaugareClientiRequest();
            inValue.Body = new app_ITP_client.ServiceReference1.AdaugareClientiRequestBody();
            inValue.Body.Id_Client = Id_Client;
            inValue.Body.Nume = Nume;
            inValue.Body.Prenume = Prenume;
            inValue.Body.Telefon = Telefon;
            inValue.Body.Email = Email;
            return ((app_ITP_client.ServiceReference1.WebService1Soap)(this)).AdaugareClientiAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        app_ITP_client.ServiceReference1.AdaugareInspectoriResponse app_ITP_client.ServiceReference1.WebService1Soap.AdaugareInspectori(app_ITP_client.ServiceReference1.AdaugareInspectoriRequest request) {
            return base.Channel.AdaugareInspectori(request);
        }
        
        public void AdaugareInspectori(int Id_Inspector, string Nume, string Prenume, string Specializare) {
            app_ITP_client.ServiceReference1.AdaugareInspectoriRequest inValue = new app_ITP_client.ServiceReference1.AdaugareInspectoriRequest();
            inValue.Body = new app_ITP_client.ServiceReference1.AdaugareInspectoriRequestBody();
            inValue.Body.Id_Inspector = Id_Inspector;
            inValue.Body.Nume = Nume;
            inValue.Body.Prenume = Prenume;
            inValue.Body.Specializare = Specializare;
            app_ITP_client.ServiceReference1.AdaugareInspectoriResponse retVal = ((app_ITP_client.ServiceReference1.WebService1Soap)(this)).AdaugareInspectori(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<app_ITP_client.ServiceReference1.AdaugareInspectoriResponse> app_ITP_client.ServiceReference1.WebService1Soap.AdaugareInspectoriAsync(app_ITP_client.ServiceReference1.AdaugareInspectoriRequest request) {
            return base.Channel.AdaugareInspectoriAsync(request);
        }
        
        public System.Threading.Tasks.Task<app_ITP_client.ServiceReference1.AdaugareInspectoriResponse> AdaugareInspectoriAsync(int Id_Inspector, string Nume, string Prenume, string Specializare) {
            app_ITP_client.ServiceReference1.AdaugareInspectoriRequest inValue = new app_ITP_client.ServiceReference1.AdaugareInspectoriRequest();
            inValue.Body = new app_ITP_client.ServiceReference1.AdaugareInspectoriRequestBody();
            inValue.Body.Id_Inspector = Id_Inspector;
            inValue.Body.Nume = Nume;
            inValue.Body.Prenume = Prenume;
            inValue.Body.Specializare = Specializare;
            return ((app_ITP_client.ServiceReference1.WebService1Soap)(this)).AdaugareInspectoriAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        app_ITP_client.ServiceReference1.AdaugareVehiculeResponse app_ITP_client.ServiceReference1.WebService1Soap.AdaugareVehicule(app_ITP_client.ServiceReference1.AdaugareVehiculeRequest request) {
            return base.Channel.AdaugareVehicule(request);
        }
        
        public void AdaugareVehicule(int id_Vehicul, string Marca, string Model, string AnFabricatie, string NumarInmatriculare) {
            app_ITP_client.ServiceReference1.AdaugareVehiculeRequest inValue = new app_ITP_client.ServiceReference1.AdaugareVehiculeRequest();
            inValue.Body = new app_ITP_client.ServiceReference1.AdaugareVehiculeRequestBody();
            inValue.Body.id_Vehicul = id_Vehicul;
            inValue.Body.Marca = Marca;
            inValue.Body.Model = Model;
            inValue.Body.AnFabricatie = AnFabricatie;
            inValue.Body.NumarInmatriculare = NumarInmatriculare;
            app_ITP_client.ServiceReference1.AdaugareVehiculeResponse retVal = ((app_ITP_client.ServiceReference1.WebService1Soap)(this)).AdaugareVehicule(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<app_ITP_client.ServiceReference1.AdaugareVehiculeResponse> app_ITP_client.ServiceReference1.WebService1Soap.AdaugareVehiculeAsync(app_ITP_client.ServiceReference1.AdaugareVehiculeRequest request) {
            return base.Channel.AdaugareVehiculeAsync(request);
        }
        
        public System.Threading.Tasks.Task<app_ITP_client.ServiceReference1.AdaugareVehiculeResponse> AdaugareVehiculeAsync(int id_Vehicul, string Marca, string Model, string AnFabricatie, string NumarInmatriculare) {
            app_ITP_client.ServiceReference1.AdaugareVehiculeRequest inValue = new app_ITP_client.ServiceReference1.AdaugareVehiculeRequest();
            inValue.Body = new app_ITP_client.ServiceReference1.AdaugareVehiculeRequestBody();
            inValue.Body.id_Vehicul = id_Vehicul;
            inValue.Body.Marca = Marca;
            inValue.Body.Model = Model;
            inValue.Body.AnFabricatie = AnFabricatie;
            inValue.Body.NumarInmatriculare = NumarInmatriculare;
            return ((app_ITP_client.ServiceReference1.WebService1Soap)(this)).AdaugareVehiculeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        app_ITP_client.ServiceReference1.AdaugareProgramareResponse app_ITP_client.ServiceReference1.WebService1Soap.AdaugareProgramare(app_ITP_client.ServiceReference1.AdaugareProgramareRequest request) {
            return base.Channel.AdaugareProgramare(request);
        }
        
        public void AdaugareProgramare(int Id_Programare, string DataProgramare, string OraProgramare, string id_Vehicul, string Id_Client, string Id_Inspector) {
            app_ITP_client.ServiceReference1.AdaugareProgramareRequest inValue = new app_ITP_client.ServiceReference1.AdaugareProgramareRequest();
            inValue.Body = new app_ITP_client.ServiceReference1.AdaugareProgramareRequestBody();
            inValue.Body.Id_Programare = Id_Programare;
            inValue.Body.DataProgramare = DataProgramare;
            inValue.Body.OraProgramare = OraProgramare;
            inValue.Body.id_Vehicul = id_Vehicul;
            inValue.Body.Id_Client = Id_Client;
            inValue.Body.Id_Inspector = Id_Inspector;
            app_ITP_client.ServiceReference1.AdaugareProgramareResponse retVal = ((app_ITP_client.ServiceReference1.WebService1Soap)(this)).AdaugareProgramare(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<app_ITP_client.ServiceReference1.AdaugareProgramareResponse> app_ITP_client.ServiceReference1.WebService1Soap.AdaugareProgramareAsync(app_ITP_client.ServiceReference1.AdaugareProgramareRequest request) {
            return base.Channel.AdaugareProgramareAsync(request);
        }
        
        public System.Threading.Tasks.Task<app_ITP_client.ServiceReference1.AdaugareProgramareResponse> AdaugareProgramareAsync(int Id_Programare, string DataProgramare, string OraProgramare, string id_Vehicul, string Id_Client, string Id_Inspector) {
            app_ITP_client.ServiceReference1.AdaugareProgramareRequest inValue = new app_ITP_client.ServiceReference1.AdaugareProgramareRequest();
            inValue.Body = new app_ITP_client.ServiceReference1.AdaugareProgramareRequestBody();
            inValue.Body.Id_Programare = Id_Programare;
            inValue.Body.DataProgramare = DataProgramare;
            inValue.Body.OraProgramare = OraProgramare;
            inValue.Body.id_Vehicul = id_Vehicul;
            inValue.Body.Id_Client = Id_Client;
            inValue.Body.Id_Inspector = Id_Inspector;
            return ((app_ITP_client.ServiceReference1.WebService1Soap)(this)).AdaugareProgramareAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        app_ITP_client.ServiceReference1.AdaugareRezultateInspectiiResponse app_ITP_client.ServiceReference1.WebService1Soap.AdaugareRezultateInspectii(app_ITP_client.ServiceReference1.AdaugareRezultateInspectiiRequest request) {
            return base.Channel.AdaugareRezultateInspectii(request);
        }
        
        public void AdaugareRezultateInspectii(int Id_Inspectie, string Status, string Observatii, string Id_Programare) {
            app_ITP_client.ServiceReference1.AdaugareRezultateInspectiiRequest inValue = new app_ITP_client.ServiceReference1.AdaugareRezultateInspectiiRequest();
            inValue.Body = new app_ITP_client.ServiceReference1.AdaugareRezultateInspectiiRequestBody();
            inValue.Body.Id_Inspectie = Id_Inspectie;
            inValue.Body.Status = Status;
            inValue.Body.Observatii = Observatii;
            inValue.Body.Id_Programare = Id_Programare;
            app_ITP_client.ServiceReference1.AdaugareRezultateInspectiiResponse retVal = ((app_ITP_client.ServiceReference1.WebService1Soap)(this)).AdaugareRezultateInspectii(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<app_ITP_client.ServiceReference1.AdaugareRezultateInspectiiResponse> app_ITP_client.ServiceReference1.WebService1Soap.AdaugareRezultateInspectiiAsync(app_ITP_client.ServiceReference1.AdaugareRezultateInspectiiRequest request) {
            return base.Channel.AdaugareRezultateInspectiiAsync(request);
        }
        
        public System.Threading.Tasks.Task<app_ITP_client.ServiceReference1.AdaugareRezultateInspectiiResponse> AdaugareRezultateInspectiiAsync(int Id_Inspectie, string Status, string Observatii, string Id_Programare) {
            app_ITP_client.ServiceReference1.AdaugareRezultateInspectiiRequest inValue = new app_ITP_client.ServiceReference1.AdaugareRezultateInspectiiRequest();
            inValue.Body = new app_ITP_client.ServiceReference1.AdaugareRezultateInspectiiRequestBody();
            inValue.Body.Id_Inspectie = Id_Inspectie;
            inValue.Body.Status = Status;
            inValue.Body.Observatii = Observatii;
            inValue.Body.Id_Programare = Id_Programare;
            return ((app_ITP_client.ServiceReference1.WebService1Soap)(this)).AdaugareRezultateInspectiiAsync(inValue);
        }
        
        public void StergereProgramare(int Id_Programare) {
            base.Channel.StergereProgramare(Id_Programare);
        }
        
        public System.Threading.Tasks.Task StergereProgramareAsync(int Id_Programare) {
            return base.Channel.StergereProgramareAsync(Id_Programare);
        }
        
        public void StergereRezultateInspectii(int Id_Inspectie) {
            base.Channel.StergereRezultateInspectii(Id_Inspectie);
        }
        
        public System.Threading.Tasks.Task StergereRezultateInspectiiAsync(int Id_Inspectie) {
            return base.Channel.StergereRezultateInspectiiAsync(Id_Inspectie);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        app_ITP_client.ServiceReference1.ModificareProgramareResponse app_ITP_client.ServiceReference1.WebService1Soap.ModificareProgramare(app_ITP_client.ServiceReference1.ModificareProgramareRequest request) {
            return base.Channel.ModificareProgramare(request);
        }
        
        public void ModificareProgramare(int Id_Programare, string DataProgramare, string OraProgramare, int id_Vehicul, int Id_Client, int Id_Inspector) {
            app_ITP_client.ServiceReference1.ModificareProgramareRequest inValue = new app_ITP_client.ServiceReference1.ModificareProgramareRequest();
            inValue.Body = new app_ITP_client.ServiceReference1.ModificareProgramareRequestBody();
            inValue.Body.Id_Programare = Id_Programare;
            inValue.Body.DataProgramare = DataProgramare;
            inValue.Body.OraProgramare = OraProgramare;
            inValue.Body.id_Vehicul = id_Vehicul;
            inValue.Body.Id_Client = Id_Client;
            inValue.Body.Id_Inspector = Id_Inspector;
            app_ITP_client.ServiceReference1.ModificareProgramareResponse retVal = ((app_ITP_client.ServiceReference1.WebService1Soap)(this)).ModificareProgramare(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<app_ITP_client.ServiceReference1.ModificareProgramareResponse> app_ITP_client.ServiceReference1.WebService1Soap.ModificareProgramareAsync(app_ITP_client.ServiceReference1.ModificareProgramareRequest request) {
            return base.Channel.ModificareProgramareAsync(request);
        }
        
        public System.Threading.Tasks.Task<app_ITP_client.ServiceReference1.ModificareProgramareResponse> ModificareProgramareAsync(int Id_Programare, string DataProgramare, string OraProgramare, int id_Vehicul, int Id_Client, int Id_Inspector) {
            app_ITP_client.ServiceReference1.ModificareProgramareRequest inValue = new app_ITP_client.ServiceReference1.ModificareProgramareRequest();
            inValue.Body = new app_ITP_client.ServiceReference1.ModificareProgramareRequestBody();
            inValue.Body.Id_Programare = Id_Programare;
            inValue.Body.DataProgramare = DataProgramare;
            inValue.Body.OraProgramare = OraProgramare;
            inValue.Body.id_Vehicul = id_Vehicul;
            inValue.Body.Id_Client = Id_Client;
            inValue.Body.Id_Inspector = Id_Inspector;
            return ((app_ITP_client.ServiceReference1.WebService1Soap)(this)).ModificareProgramareAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        app_ITP_client.ServiceReference1.ModificareClientiResponse app_ITP_client.ServiceReference1.WebService1Soap.ModificareClienti(app_ITP_client.ServiceReference1.ModificareClientiRequest request) {
            return base.Channel.ModificareClienti(request);
        }
        
        public void ModificareClienti(int Id_Client, string Nume, string Prenume, string Telefon, string Email) {
            app_ITP_client.ServiceReference1.ModificareClientiRequest inValue = new app_ITP_client.ServiceReference1.ModificareClientiRequest();
            inValue.Body = new app_ITP_client.ServiceReference1.ModificareClientiRequestBody();
            inValue.Body.Id_Client = Id_Client;
            inValue.Body.Nume = Nume;
            inValue.Body.Prenume = Prenume;
            inValue.Body.Telefon = Telefon;
            inValue.Body.Email = Email;
            app_ITP_client.ServiceReference1.ModificareClientiResponse retVal = ((app_ITP_client.ServiceReference1.WebService1Soap)(this)).ModificareClienti(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<app_ITP_client.ServiceReference1.ModificareClientiResponse> app_ITP_client.ServiceReference1.WebService1Soap.ModificareClientiAsync(app_ITP_client.ServiceReference1.ModificareClientiRequest request) {
            return base.Channel.ModificareClientiAsync(request);
        }
        
        public System.Threading.Tasks.Task<app_ITP_client.ServiceReference1.ModificareClientiResponse> ModificareClientiAsync(int Id_Client, string Nume, string Prenume, string Telefon, string Email) {
            app_ITP_client.ServiceReference1.ModificareClientiRequest inValue = new app_ITP_client.ServiceReference1.ModificareClientiRequest();
            inValue.Body = new app_ITP_client.ServiceReference1.ModificareClientiRequestBody();
            inValue.Body.Id_Client = Id_Client;
            inValue.Body.Nume = Nume;
            inValue.Body.Prenume = Prenume;
            inValue.Body.Telefon = Telefon;
            inValue.Body.Email = Email;
            return ((app_ITP_client.ServiceReference1.WebService1Soap)(this)).ModificareClientiAsync(inValue);
        }
    }
}
